name: Terraform Deploy S3 Bucket

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    AWS_REGION: us-east-1

jobs:
    terraform:
        runs-on: ubuntu-latest
        environment: dev

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: latest

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Terraform Init
              env:
                  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  TF_VAR_aws_region: us-east-1
              run: terraform init

            - name: Terraform Plan
              env:
                  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  TF_VAR_aws_region: us-east-1
              run: terraform plan -out=tfplan

            - name: Terraform Apply
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              env:
                  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  TF_VAR_aws_region: us-east-1
              run: terraform apply -auto-approve tfplan

            - name: Set up Node.js
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              uses: actions/setup-node@v3
              with:
                  node-version: '22'
                  cache: 'npm'
                  cache-dependency-path: react-app-tesla/package-lock.json

            - name: Install dependencies
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: |
                  cd react-app-tesla
                  npm ci

            - name: Build React app
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: |
                  cd react-app-tesla
                  npm run build

            - name: Deploy to S3
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: |
                  aws s3 sync react-app-tesla/dist/ s3://mo-sandbox-s3-bucket-ga --delete --exact-timestamps
